FROM busybox:1.36.1-uclibc as busybox

FROM gtfs-vp-to-file:native.0.0.1-SNAPSHOT

COPY --from=busybox /bin/sh /bin/sh
COPY --from=busybox /bin/mkdir /bin/mkdir
COPY --from=busybox /bin/chown /bin/chown

USER root
RUN mkdir /data
RUN chown -R cnb:cnb /data
USER cnb

ENV PORT 8080
EXPOSE 8080